# Generated by Django 4.1.6 on 2023-10-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libraryName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('minCapacity', models.IntegerField()),
                ('maxCapacity', models.IntegerField()),
                ('noiseLevel', models.IntegerField()),
                ('libraryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.library')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('libraryName', models.CharField(max_length=100)),
                ('roomId', models.IntegerField()),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.student')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenityName', models.CharField(max_length=100)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.room')),
            ],
            options={
                'unique_together': {('roomId', 'amenityName')},
            },
        ),
    ]
