# Generated by Django 4.1.6 on 2023-12-02 05:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_reservations_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='studentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test.student'),
        ),
    ]
